package capability

import (
	"bytes"
	"fmt"
	"strings"
)

// GenerateMarkdown renders the deterministic public capability reference.
func GenerateMarkdown(definitions []Definition) ([]byte, error) {
	if err := Validate(definitions); err != nil {
		return nil, fmt.Errorf("validate capability registry: %w", err)
	}
	definitions = append([]Definition(nil), definitions...)
	definitions = sorted(definitions)

	var output bytes.Buffer
	output.WriteString("<!-- Code generated by cmd/gencapdocs. DO NOT EDIT. -->\n\n")
	output.WriteString("# Capability reference\n\n")
	output.WriteString("This reference derives from the executable capability registry.\n")
	output.WriteString("Use `tadx capability get <id>` for the same focused metadata at runtime.\n\n")
	output.WriteString("## Capability summary\n\n")
	output.WriteString("| Capability ID | Owner | Disposition | Verification | Implementation | Command |\n")
	output.WriteString("| --- | --- | --- | --- | --- | --- |\n")
	for _, definition := range definitions {
		fmt.Fprintf(&output, "| `%s` | %s | %s | %s | %s | %s |\n",
			escapeTable(definition.ID), escapeTable(string(definition.Owner)), escapeTable(string(definition.Disposition)),
			escapeTable(string(definition.Verification)), escapeTable(string(definition.Implementation)), escapeTable(command(definition)))
	}
	output.WriteString("\n## Capability definitions\n\n")
	for _, definition := range definitions {
		fmt.Fprintf(&output, "### `%s`\n\n", definition.ID)
		fmt.Fprintf(&output, "%s\n\n", definition.Outcome)
		fields := [][2]string{
			{"Surface", definition.Surface},
			{"Operation type", string(definition.Type)},
			{"Owner", string(definition.Owner)},
			{"Selectors", definition.Selectors},
			{"Products and availability", definition.Availability},
			{"Product disposition", string(definition.Disposition)},
			{"Evidence level", string(definition.EvidenceLevel)},
			{"Verification readiness", string(definition.Verification)},
			{"Implementation state", string(definition.Implementation)},
			{"Local write", yesNo(definition.LocalWrite)},
			{"Remote mutation", yesNo(definition.RemoteMutation)},
			{"Supports `--preview`", yesNo(definition.SupportsPreview)},
			{"Raw capable", yesNo(definition.RawCapable)},
			{"Safety and guard", definition.SafetyGuard},
			{"Artifact effect", definition.ArtifactEffect},
			{"Upstream operation", definition.Upstream},
			{"Evidence", definition.Evidence},
			{"Validation or blocker", definition.Validation},
			{"Blocker ID", emptyAsNone(string(definition.Blocker))},
			{"Command binding", command(definition)},
		}
		for _, field := range fields {
			fmt.Fprintf(&output, "- %s: %s\n", field[0], field[1])
		}
		output.WriteByte('\n')
	}
	return bytes.TrimSuffix(output.Bytes(), []byte("\n")), nil
}

func sorted(definitions []Definition) []Definition {
	result := make([]Definition, len(definitions))
	for index, definition := range definitions {
		result[index] = clone(definition)
	}
	// All registry callers use the same stable ordering implementation.
	return sortDefinitions(result)
}

func sortDefinitions(definitions []Definition) []Definition {
	for current := 1; current < len(definitions); current++ {
		for previous := current; previous > 0 && definitions[previous].ID < definitions[previous-1].ID; previous-- {
			definitions[previous], definitions[previous-1] = definitions[previous-1], definitions[previous]
		}
	}
	return definitions
}

func command(definition Definition) string {
	if len(definition.CommandPath) == 0 {
		return "None"
	}
	return "`tadx " + strings.Join(definition.CommandPath, " ") + "`"
}

func escapeTable(value string) string { return strings.ReplaceAll(value, "|", "\\|") }
func emptyAsNone(value string) string {
	if value == "" {
		return "None"
	}
	return value
}
func yesNo(value bool) string {
	if value {
		return "Yes"
	}
	return "No"
}
