"""Test assessment inventory tooling without reading Git objects or live services."""

import importlib.util
from pathlib import Path
import subprocess
import unittest
from unittest import mock


SPEC = importlib.util.spec_from_file_location(
    "collect_inventory", Path(__file__).with_name("collect_inventory.py")
)
collector = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(collector)

COMMIT = "a" * 40


def tree_entry(path, oid, object_type="blob"):
    return f"100644 {object_type} {oid}\t{path}".encode() + b"\0"


def batch_blob(oid, data):
    return f"{oid} blob {len(data)}\n".encode() + data + b"\n"


class FilenameHintsTest(unittest.TestCase):
    def test_hints_follow_filename_precedence_not_semantic_production_claims(self):
        cases = {
            "actions/demo/action.go": "go_non_test",
            "actions/demo/action_test.go": "test",
            "internal/demo/test_helpers.go": "go_non_test",
            "internal/demo/testdata/helper_test.go": "fixture",
            "fixtures/example.go": "fixture",
            "scripts/inventory.go": "tooling_or_automation",
            "scripts/inventory_test.go": "test",
            "cmd/gencapdocs/main.go": "tooling_or_automation",
            ".github/workflows/check.yml": "tooling_or_automation",
            ".agents/skills/example/SKILL.md": "tooling_or_automation",
            "web/tests/example.js": "test",
            "web/example.test.mjs": "test",
            "docs/guide.md": "documentation_or_site",
            "docs/site.html": "documentation_or_site",
            "docs/chart.svg": "documentation_or_site",
            "docs/map.excalidraw": "documentation_or_site",
            "go.mod": "other",
        }
        for path, expected in cases.items():
            with self.subTest(path=path):
                self.assertEqual(expected, collector.kind(path))

    def test_areas_group_by_owner_not_operation_depth(self):
        cases = {
            "actions/project/create/action.go": "actions.project",
            "actions/project/move/action.go": "actions.project",
            "internal/resources/project/adapter.go": "internal.resources",
            "cmd/tadx/main.go": "cmd.tadx",
            "docs/architecture/guide.md": "docs",
            ".agents/skills/example/SKILL.md": ".agents",
            "AGENTS.md": "repository-root",
        }
        for path, expected in cases.items():
            with self.subTest(path=path):
                self.assertEqual(expected, collector.area(path))


class GitInventoryTest(unittest.TestCase):
    def run_inventory(self, tree, batch):
        git = mock.Mock(side_effect=[(COMMIT + "\n").encode(), tree])
        result = subprocess.CompletedProcess(["git"], 0, stdout=batch, stderr=b"")
        with mock.patch.object(collector, "git", git), mock.patch.object(
            collector.subprocess, "run", return_value=result
        ) as run:
            report = collector.inventory("pinned-revision")
        self.assertEqual(
            [mock.call("rev-parse", "--verify", "pinned-revision^{commit}"),
             mock.call("ls-tree", "-rz", "--full-tree", COMMIT)],
            git.call_args_list,
        )
        return report, run

    def test_mocked_git_inventory_counts_and_excludes_archived_contents(self):
        sources = [
            ("actions/project/action.go", b"package project\n\nvar Value = 1\n"),
            ("actions/project/action_test.go", b"package project\n\nfunc TestChange(t *testing.T) {}\nfunc BenchmarkChange(b *testing.B) {}\nfunc FuzzChange(f *testing.F) {}\nfunc ExampleChange() {}\nfunc helper() {}\n"),
            ("actions/project/generated.go", b"// Code generated by fixture. DO NOT EDIT.\npackage project\n"),
            ("cmd/gencapdocs/main.go", b"package main\n"),
            ("actions/project/testdata/sample_test.go", b"package sample\nfunc TestFixture(t *testing.T) {}\n"),
            ("docs/a guide.md", b"# Guide\n"),
            ("assets/nul.bin", b"binary\0data\n"),
            ("assets/non_utf8.bin", b"\xff\xfe\n"),
        ]
        entries = [(path, f"{index:040x}", data)
                   for index, (path, data) in enumerate(sources, 1)]
        archived_oid = "f" * 40
        tree = b"".join(tree_entry(path, oid) for path, oid, _ in entries)
        tree += tree_entry("archived/old.go", archived_oid)
        batch = b"".join(batch_blob(oid, data) for _, oid, data in entries)
        report, run = self.run_inventory(tree, batch)

        run.assert_called_once_with(
            ["git", "cat-file", "--batch"],
            input="".join(oid + "\n" for _, oid, _ in entries).encode(),
            stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=True,
        )
        self.assertNotIn(archived_oid.encode(), run.call_args.kwargs["input"])
        self.assertEqual(COMMIT, report["source_revision"])
        self.assertEqual({
            "tracked_files_in_scope": 8,
            "archived_paths_excluded": 1,
            "kind_hints": {"documentation_or_site": 1, "fixture": 1,
                           "go_non_test": 2, "other": 2, "test": 1,
                           "tooling_or_automation": 1},
            "go_files": 5,
            "go_non_test_files": 3,
            "go_test_files": 2,
            "go_non_test_lines": 6,
            "go_test_lines": 9,
            "go_non_test_directories": 2,
            "go_test_declarations": 5,
        }, report["summary"])
        self.assertEqual({"files": 4, "go_non_test": 2, "go_test": 2,
                          "go_lines": 14, "test_declarations": 5},
                         report["areas"]["actions.project"])
        rows = {row["path"]: row for row in report["files"]}
        self.assertTrue(rows["actions/project/generated.go"]["generated_header"])
        self.assertFalse(rows["actions/project/action.go"]["generated_header"])
        for path in ["assets/nul.bin", "assets/non_utf8.bin"]:
            self.assertIsNone(rows[path]["physical_lines"])
            self.assertNotIn("declarations", rows[path])
        self.assertEqual([
            {"name": "TestChange", "line": 3},
            {"name": "BenchmarkChange", "line": 4},
            {"name": "FuzzChange", "line": 5},
            {"name": "ExampleChange", "line": 6},
        ], rows["actions/project/action_test.go"]["declarations"])
        self.assertIn("not semantic", report["method"]["kind_hint"])
        self.assertIn("not executed", report["method"]["declarations"])
        self.assertIn("does not mean shipped", report["method"]["go_non_test"])

    def test_empty_committed_tree_has_zero_counts(self):
        report, run = self.run_inventory(b"", b"")
        self.assertEqual([], report["files"])
        self.assertEqual({}, report["areas"])
        self.assertEqual(0, report["summary"]["go_non_test_directories"])
        self.assertEqual(0, report["summary"]["go_test_declarations"])
        self.assertEqual(b"", run.call_args.kwargs["input"])

    def test_non_blob_entry_is_rejected_before_content_read(self):
        tree = tree_entry("third_party/submodule", "b" * 40, "commit")
        with mock.patch.object(collector, "git", side_effect=[COMMIT.encode(), tree]), \
                mock.patch.object(collector.subprocess, "run") as run:
            with self.assertRaisesRegex(ValueError, "Unsupported non-blob entry"):
                collector.inventory("pinned-revision")
        run.assert_not_called()

    def test_invalid_batch_responses_are_rejected(self):
        oid = "b" * 40
        tree = tree_entry("main.go", oid)
        cases = {
            "missing object": (f"{oid} missing\n".encode(), "Unexpected cat-file response"),
            "wrong object": (batch_blob("c" * 40, b"x"), "Unexpected cat-file response"),
            "wrong type": (f"{oid} tree 1\nx\n".encode(), "Unexpected cat-file response"),
            "bad terminator": (f"{oid} blob 1\nx!".encode(), "Invalid blob terminator"),
            "truncated blob": (f"{oid} blob 5\nx".encode(), "Invalid blob terminator"),
            "trailing data": (batch_blob(oid, b"x") + b"extra", "Unexpected trailing batch data"),
        }
        for name, (batch, error) in cases.items():
            with self.subTest(name=name), self.assertRaisesRegex(ValueError, error):
                self.run_inventory(tree, batch)

    def test_git_failures_propagate_without_partial_report(self):
        failure = subprocess.CalledProcessError(128, ["git", "rev-parse"])
        with mock.patch.object(collector, "git", side_effect=failure), \
                mock.patch.object(collector.subprocess, "run") as run:
            with self.assertRaises(subprocess.CalledProcessError):
                collector.inventory("missing-revision")
        run.assert_not_called()


if __name__ == "__main__":
    unittest.main()
